### ISSUE TITLE
About the dataset

### ISSUE THREAD

**Issue by liuxi1234** [zhaobinglei/REGNet_for_3D_Grasping#1]
Can you give a detailed description of the production process of the dataset used?Thanks

**Comment by zhaobinglei** [comment]
The old dataset has only about 200 grasps in each scene. In the last week I
will share a new dataset.
The data generation involves 4 steps.(1) simulate scenes and render
observed point cloud (2)construct collision-free grasps. (3) obtain grasp
quality scores (4) compute point grasp confidence for each point in the
observed point cloud. The code is based on the S4G.
Best wishes,
Binglei

liuxi1234 ***@***.***> 于2021年4月29日周四 上午10:16写道：

**Comment by zhaobinglei** [comment]
Same as the #3
The link to the new dataset is https://pan.baidu.com/s/1alwaKQZt0IGE11FFSClxOg . And the extraction code is x79a. (Maybe you can only use a Chinese proxy to access the link.)
