### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by zhanglinmei** [zhaobinglei/REGNet_for_3D_Grasping#2]
Can you share the data set? Thank you

**Comment by zhaobinglei** [comment]
The old dataset has only about 200 grasps in each scene. In the last week I
will share a new dataset.
Best wishes,
Binglei

zhanglinmei ***@***.***> 于2021年5月14日周五 上午10:33写道：

**Comment by zhaobinglei** [comment]
Same as the #3 
The link to the new dataset is https://pan.baidu.com/s/1alwaKQZt0IGE11FFSClxOg . And the extraction code is x79a. (Maybe you can only use a Chinese proxy to access the link.)

**Comment by zhaobinglei** [comment]
Same as the #3
The link to the new dataset is https://pan.baidu.com/s/1alwaKQZt0IGE11FFSClxOg . And the extraction code is x79a. (Maybe you can only use a Chinese proxy to access the link.)
