### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by PicklesXiaoLin** [zhaobinglei/REGNet_for_3D_Grasping#3]
Hello, can you share your dataset?
Thank you~

**Comment by zhaobinglei** [comment]
The old dataset has only about 200 grasps in each scene. In the last week I
will share a new dataset.
Best wishes,
Binglei

PicklesXiaoLin ***@***.***> 于2021年5月17日周一 上午9:01写道：

**Comment by zhaobinglei** [comment]
The link of the new dataset is https://pan.baidu.com/s/1alwaKQZt0IGE11FFSClxOg . And the extraction code is x79a. (Maybe you can only use a Chinese proxy to access the link.)
